databases:
  - name: my-app-db
    plan: free
    databaseName: portfolio
    user: portfolio

services:
  - type: web
    name: kushal-portfolio
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "Kushal Portfolio"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: my-app-db
          property: connectionString
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: public
      - key: MAIL_MAILER
        value: resend
      - key: MAIL_FROM_ADDRESS
        value: hello@kushalghimire57.com.np
      - key: MAIL_FROM_NAME
        value: "Kushal Portfolio"
      - key: RESEND_API_KEY
        sync: false
      - key: CLOUDINARY_URL
        sync: false
